version: "3.7"

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8081:8081"
   
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d2q37p3e5dus73bk5vsg-a.oregon-postgres.render.com:5432/onlinequiz_wyjs?sslmode=require
      SPRING_DATASOURCE_USERNAME: onlinequiz_wyjs_user
      SPRING_DATASOURCE_PASSWORD: 18N3iNR1bCmXMITUA6ewApv92tXBJdtZ
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - springboot-net

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: onlinequiz_wyjs
      POSTGRES_USER: onlinequiz_wyjs_user
      POSTGRES_PASSWORD: 18N3iNR1bCmXMITUA6ewApv92tXBJdtZ
    ports:
      - "5432:5432"

    networks:
      - springboot-net



networks:
  springboot-net:
